# Pharmacoepidemiology simulation study practices: A review of the literature

This is the official source code repository of the review of simulation practices in the Journal Pharmacoepidemiology and Drug Safety.

## Protocol

The protocol of the study can be found here: [Protocol](../2.1.a_i.emulat_sim_brief/reports/emulat_sim_protocol.pdf)

## Functionality

The following two scripts were used:

-   search_and_download.R
-   match_included.R

To replicate our results, use the following: 

1. search_and_download.R should be called first which downloads the metadata for the simulation studies using easyPubMed and stores the data in an XML file for importing to Covidence. It also obtains the extracted data from [Tazare et al.](https://doi.org/10.1002/pds.5856) and creates another XML file for importing to Covidence. 

2. Both XML files are then imported to Covidence for screening. 

3. After screening, the metadata from the included articles is exported from Covidence as a CSV file.

4. match_included.R should then be called which matches the included PMIDs from screening to the raw metadata files from our search and Tazare et al. 

5. A file named included_final.csv then contains the included articles from which we extracted the data.

## Citation

If you use this code in your research, please cite it like this:

```         
@article {Muddiman2025.04.30.25326427,
	author = {Muddiman, Ryan and Aiello Battan, Florencia Ines and Tazare, John and Schultze, Anna and Boland, Fiona and Perez, Teresa and Wei, Li and Walsh, Mary E. and Moriarty, Frank},
	title = {Pharmacoepidemiology simulation study practices: A methodological review},
	elocation-id = {2025.04.30.25326427},
	year = {2025},
	doi = {10.1101/2025.04.30.25326427},
	publisher = {Cold Spring Harbor Laboratory Press}
	URL = {https://www.medrxiv.org/content/early/2025/05/02/2025.04.30.25326427},
	eprint = {https://www.medrxiv.org/content/early/2025/05/02/2025.04.30.25326427.full.pdf},
	journal = {medRxiv}
}

```

## License

TBD
