## Medications and individual factors associated with serotonin syndrome: an overview of review

Serotonin syndrome is a potentially lethal adverse drug reaction caused by exposure to one or more serotonin-elevating medications. An excess of serotonin can cause non-specific symptoms ranging from mild (nervousness, diarrhoea, shivering, myoclonus), to severe (high fever, muscle rigidity), and rarely death. Its burden is unknown due to the absence of official diagnostic criteria, under-reporting and symptom overlap with other syndromes. In addition to diagnostic uncertainty, there is also no consensus on which drugs can cause serotonin syndrome.

In this study, we aim to summarise the published literature on the medications and factors associated with serotonin syndrome. A greater understanding of both the medications and signs and clinical features involved could help healthcare professionals and patients identify mild symptoms earlier, particularly in high-risk groups, and thus allow intervention at an early stage. It could also reduce potential risk as part of medication reviews in patients taking multiple medicines.

## **The objectives of this review are:**

1.  To summarise published systematic review evidence on prescribed medicines commonly associated with serotonin syndrome and,
2.  To determine the reported incidence of serotonin syndrome,
3.  To identify: the secondary drugs or drug classes (through interaction with another drug), the patients characteristics, and other risk factors commonly associated with serotonin syndrome.

## **Protocol**

The published protocol is available [here](https://wellcomeopenresearch.org/articles/10-475) and a live version [here](https://osf.io/4rf86/overview).
