project:
  type: website
  output-dir: docs

website:
  title: "DIAMOND"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Workpackages/WP_1.qmd
        text: WP1
      - href: Workpackages/WP_2.qmd
        text: WP2
      - href: Workpackages/WP_3.qmd
        text: WP3
      - href: Workpackages/WP_4.qmd
        text: WP4
    logo: "assets/imgs/Diamond-Logo.png"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true