project:
  type: website
  output-dir: docs

website:
  title: "today"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Workpackages/WP_1.qmd
        text: WP1
      - href: Workpackages/WP_2.qmd
        text: WP2

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true