name: Quarto Publish

on:
  push:
    branches: ["main"]

permissions:
  contents: write   # changed from read → write (so it can commit)
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # keeps git credentials for committing

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install base R packages
        run: |
          Rscript -e 'install.packages(c(
            "knitr", 
            "rmarkdown"
          ))'

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Project
        run: quarto render

      # --- New Step: Commit built files back to repo ---
      - name: Commit rendered site to docs/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update rendered site [skip ci]"
          git push origin main

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
